# Generated by Django 3.1.7 on 2021-02-27 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidItems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biditem',
            old_name='author',
            new_name='user',
        ),
    ]
