# Generated by Django 3.1.7 on 2021-02-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidItems', '0002_auto_20210227_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biditemauthor',
            old_name='biditem',
            new_name='bidItem',
        ),
    ]
