# Generated by Django 3.1.7 on 2021-03-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidItems', '0003_auto_20210227_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='biditem',
            name='finalPrice',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
