# Generated by Django 3.1.7 on 2021-03-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidItems', '0004_biditem_finalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biditem',
            name='finalPrice',
            field=models.FloatField(blank=True),
        ),
    ]
