# Generated by Django 3.1.7 on 2021-03-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidItems', '0007_biditem_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='biditem',
            name='hash',
            field=models.TextField(default='faafd'),
            preserve_default=False,
        ),
    ]
