# Generated by Django 3.1.7 on 2021-03-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidItems', '0008_biditem_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biditem',
            name='hash',
            field=models.TextField(blank=True, null=True),
        ),
    ]
